import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import { Inter } from 'next/font/google';
import './globals.css';

// Initialize Inter font with bold weight
const inter = Inter({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-inter', // This creates a CSS variable we can use
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} ${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
